# Generated by Django 5.1.1 on 2025-01-02 20:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("money", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="clints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("tex", models.BigIntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("number", models.CharField(max_length=255, null=True)),
                ("is_company", models.BooleanField(default=0)),
                ("company", models.TextField(blank=True, null=True)),
                (
                    "total_paied",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                    ),
                ),
                (
                    "total_buy",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999),
                        ],
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999),
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=36, unique=True),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="clints/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_clint",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClintPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(default="None")),
                (
                    "payment_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="clints/pymnets/"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.moneysource",
                    ),
                ),
                (
                    "clint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clints.clints"
                    ),
                ),
            ],
        ),
    ]
