# Generated by Django 5.1.1 on 2025-01-02 20:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("employe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Account"),
                            ("bank", "Bank Account"),
                            ("company_bank", "Company Bank Account"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sorcePyment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("note", models.TextField()),
                ("payment_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.moneysource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeneralPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField()),
                ("payment_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "source",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.moneysource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerPaymentUsd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, null=True)),
                ("payment_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Customer/pymnets/usd/"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.costomers",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.moneysource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerPaymentTl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, null=True)),
                ("payment_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Customer/pymnets/tl/"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.costomers",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.moneysource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployePayment",
            fields=[
                (
                    "sorcepyment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="money.sorcepyment",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("money.sorcepyment",),
        ),
    ]
